### ISSUE TITLE
fatal: Out of memory? mmap failed: No such device

### ISSUE THREAD

**Issue by bealdav** [akretion/voodoo#13]
If you have this message, you can't run your voodoo.

To solve it:
- Go out of voodoo
- Delete this line in your voodoo.yml: 
```bash
- ./gitconfig:/home/devstep/.gitconfig'
```
- apply these cmd to customize :
```bash
git config --global user.name "Fantomas" 
git config --global user.email "d@s.fr"
```
- Back to voodoo with voodoo run
- If  ```ak run``` is ok, you can put voodoo.yml to its intial state

**Comment by sebastienbeau** [comment]
Please remove from everywhere the mount of gitconfig
https://github.com/akretion/voodoo/commit/01cac3010ebd0d4a6e887fafc6d6c7e69bfb0581

You can add the "gitconfig: ~/.gitconfig" in your .voodoo/config.yml
