### ISSUE TITLE
infrastructure provider option

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#14]
add a voodoo or ak command that will add a .kitchen.yml file from a template, according to a specific provider: ssh, vagrant, aws, ovh so that tests or deploy can be achieved with just bundle exec kitchen converge.

**Comment by bealdav** [comment]
:+1:

**Comment by sebastienbeau** [comment]
This is not mandatory anymore. deploy can be done via git push on waht you want or simply via voodoo deploy
