### ISSUE TITLE
welcome message is messed

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#15]
Since recently, it seems that the branded welcome message (the ASCII art with Akretion and Anybox mentioned) is messed.

It seems that 1st time you do voodoo run it works, but then, on subsequent voodoo run it's messed.

It's just a graphical glitch, possibly an issue with the line size that mess the ASCII art. No a big deal but to be fixed before public release.

**Comment by rvalyi** [comment]
Actually it's possible this only happens with recent version of Docker or docker-compose.

**Comment by sebastienbeau** [comment]
this bug seem to be solve, reopen if needed
