### ISSUE TITLE
apt packages support

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#16]
See if we can use an Aptfiles and this buildpack to install apt-packages on the fly (possibly caching the apt-cache in the persistent project directory:
https://github.com/ddollar/heroku-buildpack-apt

**Comment by bealdav** [comment]
couldn't be solved with docker-compose to have less dependencies ?
If yes we need to document it, isn't it ?

**Comment by sebastienbeau** [comment]
Solve by using DockerFile see here : https://github.com/akretion/voodoo/wiki/Install-custom-debian-package
