### ISSUE TITLE
shared_eggs = True in voodoo.yml

### ISSUE THREAD

**Issue by bealdav** [akretion/voodoo#22]
voodoo.yml:

```
    shared_eggs = True
```

When I build, with this config, it freeze. It stops to the last repo git downloaded but in fact the problem is after, because git source are here.

`shared_eggs = False` solve the problem
---

Description:    Ubuntu 15.04

docker version
Client version: 1.7.1

**Comment by sebastienbeau** [comment]
I config that we have something strange when the eggs is build, after some investigation it's seem that buildout try to install odoo in develop mode and sometime it break, need more investigation

**Comment by sebastienbeau** [comment]
I do not have any more issue with the last version of ubuntu and buildout
