### ISSUE TITLE
Add nginx magic

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/voodoo#23]
The idea will to add some additionnal magic to voodoo by configuring automatically the port and configuring nginx so you can have something like

http://localhost/my_odoo_project_1
http://localhost/my_odoo_project_2
http://localhost/my_odoo_project_3
...

It seem that this is already developped : https://github.com/jwilder/nginx-proxy

So we just need to use it and no more port configuration

**Comment by sebastienbeau** [comment]
alternative using haproxy : http://jasonwilder.com/blog/2014/07/15/docker-service-discovery/

**Comment by rvalyi** [comment]
:-1: I think it's better to go with clodoo if you want to run several projects at the same time. I quite never see this need on the development work station.

**Comment by bealdav** [comment]
if you're a lot of people on a project, i think it's really useful :+1:

**Comment by sebastienbeau** [comment]
@rvalyi I think there is a misunderstood, this is not for the dev version or the preprod for the customer. For this for sure we go with clodoo. Here is for the local workstation. You are working on a customer A project, than customer B call you for an emergency then you just want to run voodoo run and go to localhost/customer_B/odoo 

It can also simplify the multi-docker issue. Indeed if you launch voodoo that run odoo, magento and mailcatcher it will be easier to have 

http://localhost/customer_B/odoo
http://localhost/customer_B/magento
http://localhost/customer_B/mailcatcher
http://localhost/customer_B/ionic_apps

or maybe

http://odoo.customer_B
http://magento.customer_B
....

I do not know what will be the easiest solution

**Comment by rvalyi** [comment]
@sebastienbeau 
```
I think there is a misunderstood, this is not for the dev version or the preprod for the customer. For this for sure we go with clodoo
```
I always knew you would end up adopting the product codename.

Ok I understand.

**Comment by sebastienbeau** [comment]
This is done here : https://github.com/akretion/voodoo/pull/79
