### ISSUE TITLE
ak run failed

### ISSUE THREAD

**Issue by chafique-delli** [akretion/voodoo#27]
When i do 'ak run' after 'ak build', it fails with error message:

"Exception: The parameter 'runningenv' has not be set neither in base config file option -c or in openerprc. We strongly recommend against using the rc file but instead use an explicit config file with this content: [options] running_env = dev"

For fix that, i do 'bin/buildout -c buildout.dev.cfg' instead of 'ak build'.

**Comment by bealdav** [comment]
confirmed bug

**Comment by sebastienbeau** [comment]
We should rewrite ak build and always build using the buildout.dev.cfg

**Comment by sebastienbeau** [comment]
See I have fixed this issue https://github.com/akretion/voodoo-image/issues/7
The build is ok and the version of ak is up to date so just voodoo pull to get the last version
