### ISSUE TITLE
dateutil versions

### ISSUE THREAD

**Issue by jpoa** [akretion/voodoo#36]
Hey there, first of all thanks for such awesome tool.

I am getting some issues with python-dateutil==2.4.2, if I force 2.4.0 all goes well.

Am I the only one with this?

It also seems linked to this problem here: https://github.com/anybox/anybox.recipe.odoo/blob/master/anybox/recipe/odoo/base.py#L463

Cheers!

**Comment by sebastienbeau** [comment]
Hi @jpoa

Indeed there is are error with the last version python-dateutil (and also of vobject for 7 version)

I have updated the default template for 7, 8, 9 here :
https://github.com/akretion/voodoo-template/blob/7.0/buildout.cfg
https://github.com/akretion/voodoo-template/blob/8.0/buildout.cfg
https://github.com/akretion/voodoo-template/blob/9.0/buildout.cfg

We will take the time to maintain the template so it's easier to boostrap a new project

Also I have update the voodoo-image (the build was broken), https://hub.docker.com/r/akretion/voodoo/builds/
So I recommend you to run `voodoo pull ` to use the last docker image of voodoo

It's a huge pleasure for us that you use Voodoo ! Do not hesitate to ask us question or opening issue.
