### ISSUE TITLE
Instalar novos pacotes

### ISSUE THREAD

**Issue by fadeldamen** [akretion/voodoo#37]
Quero instalar dentro do projeto o aeroo-report por exemplo, onde consigo documentação ja que fiz a instalação e ao fechar e voltar a executar o voodoo ele não persiste com exepção dos arquivos dentro da pasta modulo

**Comment by bealdav** [comment]
I do not understand spanish, but it seems you mean to have aeroo dependencies in voodoo linux image ?

**Comment by fadeldamen** [comment]
I sorry, yes I need aeroo dependencein voodoo but i want undestand how to include some ware dependence aplication or package linux in image.

**Comment by bealdav** [comment]
Ok, It's a generic problem covered by docker-compose and Docker-file as far I know. @sebastienbeau please we need to document it.

**Comment by fadeldamen** [comment]
I read someware for documentation for docker-compose and Dockerfile, but whare I find there files or configuration files ?

**Comment by rvalyi** [comment]
@fadeldamen so a metade da Akretion que fala portugues, lamento. Mas esse tipo de projeto e para ser internatonal mesmo. Bom a gente usa Voodoo com o aeroo sim. Espero poder documentar isso um dia logo. Mas a ideia involve duas coisas:

1. vc precisa sim de novos pacotes. Para nao ter que re-instalar eles sempre, vc pode dar um docker commit depois de atualizar o container e criar uma nova imagem. Depois no arquivo voodoo.yml vc pode especificar essa imagem custom ao invez da imagem base akretion/voodoo

2. o outro ponto e se connectar ao servidor aeroo. Voce pode usar essa imagem Docker que eu fiz: https://github.com/akretion/aeroocker e depois vc linka esse container ao container voodoo dentro do voodoo.yml de accordo com a documentaçao do docker-compose: https://docs.docker.com/v1.8/compose/yml/#links

O Voodoo extende o Docker-compose entao quasi tudo que funciona no Docker-compose vale para o Voodoo tb.

Finalmente, para evitar de ter que criar e publiar outras imagens, a ideia e de suportar o buildpack apt no projeto pai Devstep, o issue esta aqui: https://github.com/fgrehm/devstep/issues/101

Bom espero ter ajudado.

@bealdav please learn to spot Portuguese language, it's always ugly for a Brazilian born company if we tell Brazilian guys they speak Spanish ;-p

**Comment by sebastienbeau** [comment]
Ola @fadeldamen Tudo bem ?

If you want to install new package, I found a solution for you ;) !
You have to create a customer dockerfile like this : https://github.com/sebastienbeau/voodoo-template/blob/9.0-flatoo/Dockerfile
And in your voodoo file you have to replace the key "image" by "build ." like this https://github.com/sebastienbeau/voodoo-template/blob/9.0-flatoo/voodoo.yml#L6.

If you need any help please reopen the ticket.

**Comment by fadeldamen** [comment]
Tanks beal i try
