### ISSUE TITLE
Production / Best practices

### ISSUE THREAD

**Issue by jpoa** [akretion/voodoo#38]
Greetings!

Voodoo is a priceless tool for development of Odoo, so much that I just cant think working without it! Big kudos!

I am also wondering if you guys thought that it can be used for deployment to production, either as means to deploy or as the actual server in production itself. From what I see, we can sync the project and the container and be on our way, no?

My concern would be the links for eggs and the downloads folder.

Do you have any best practices or tips/documents on this? Is this even considered or am I dreaming too high here?

Cheers!

**Comment by bealdav** [comment]
In production we use only use buildout recipe for odoo

**Comment by jpoa** [comment]
Via ak?

**Comment by rvalyi** [comment]
jpoa,

Voodoo is based on Devstep which is dev oriented (also with all the
opiniated settings we do). In production we use an other image subtsrate
called odoocker, may be you want to use it as a base image too:
https://github.com/akretion/odoocker

On Mon, Mar 7, 2016 at 4:40 PM, jpoa <notifications@github.com> wrote:

> Via ak?
> On 7 Mar 2016 17:40, "David Beal" <notifications@github.com> wrote:
>
> > In production we use only use buildout recipe for odoo
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/akretion/voodoo/issues/38#issuecomment-193337680>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akretion/voodoo/issues/38#issuecomment-193417099>.
>



-- 
Raphaël Valyi
Founder and consultant
http://twitter.com/rvalyi <http://twitter.com/#!/rvalyi>
+55 21 3942-2434
www.akretion.com

**Comment by jpoa** [comment]
Ok, that sorts me out in the right direction. I got the feeling that voodoo would be more dev oriented as you stated and was wondering what was your counterpart for deployment in production.

Thank you very much for the pointers @rvalyi and @bealdav, I will check odoocker now.
