### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by renatonlima** [akretion/voodoo#39]
When I try install voodoo I have this error:

```
ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
 
#include "pyconfig.h"
                       ^
 
compilation terminated.
 
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by sebastienbeau** [comment]
Hi Renato can you give me the full stack trace? Did the error occure when you run "ak build" ?

**Comment by renatonlima** [comment]
Hello Seb,

I try run this command: 

```
sudo pip install git+https://github.com/akretion/voodoo.git --upgrade
```

I found the problem. The problem was that I do not have python-dev installed in my environment.

**Comment by renatonlima** [comment]
I will do one PR to add it in prerequisite session in README

**Comment by sebastienbeau** [comment]
ok
