### ISSUE TITLE
option to share odoo repo like in voodoo 1

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#49]
When you have a 128 or 256 Go SSD you hardly want to spend 1 Go per Odoo project so an option to share the odoo repos like voodoo 1 would be welcome. That could be at the .voodoo user preference level and at the project level too eventually.

Yes sharing Odoo sucks for tor the odoo patches. But on the other hand we tend to patches the Odoo's of a given serie in the same way or let say it doesn't really matter in general for dev: if a patch is missing we make sure to apply it. At least in an SSD context I think it is still worthy to share the Odoo repos.

**Comment by sebastienbeau** [comment]
You can to it manually by adding a symlink to part/odoo to /home/my_user/.voodoo/shared/my_odoo_8
Every thing in the shared directory is shared in the container so you can add every wanted symlink
