### ISSUE TITLE
base image too limited...

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo#52]
Hello, I think the current base image of Voodoo v2 is too limited. No libffi, no vim, it comes short very quickly requiring you to create a Dockerfile and a custom image.

Voodoo v1 was built upon Devstep that is upon Herokuish with is the base image of teh Heroku stack and is quite a standard stack (yet bigger). This is also the kind of base image we use in production at Akretion. There is 2 issues: a larger base image and Ubuntu 14.04 based at the moment. But still I think that would be a better option forcing us less to require a custom Dockerfile. Also no Vim is a PITA IMHO. Eventually having odoo as a suoder (like developper in Devstep) would also help in dev mode...

Thoughts?

**Comment by rvalyi** [comment]
as for the libffi-dev deb package I think it's so commonly required that I added it in the default base image no matter what we decide later: https://github.com/akretion/voodoo-image/commit/91f85a7d634874f4afeb3ab5fe0eaf164cfba690

**Comment by sebastienbeau** [comment]
Indeed we can add some package, which one do you want?

**Comment by rvalyi** [comment]
I added libffi-dev and vim. Overall I think we should easily accept packages that are part of the Heroku Cedarish stack when they are missing. At the moment we are missing none here.
