### ISSUE TITLE
Voodoo 2 - Compatibility version

### ISSUE THREAD

**Issue by bealdav** [akretion/voodoo#55]
works on Ubuntu: 15.10, 16.04, 14.04

EDIT: it works with 14.04 too

**Comment by rvalyi** [comment]
hum, what doesn't work on 14.04?

**Comment by rvalyi** [comment]
here we @mbcosta had lot's of trouble getting it to work on Slackware due to the too old docker version that is packaged and doesn't do well with docker-compose.

**Comment by rvalyi** [comment]
FYI, @mbcosta successfully made it work on Debian Jessie

**Comment by bealdav** [comment]
Error on 14.04:
` client and server don't have same version (client API version: 1.22, server API version: 1.19)`

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

```

**Comment by rvalyi** [comment]
looks like a Docker error indeed... Did you try to update the docker server package on this instance?

**Comment by rvalyi** [comment]
NOTE: this is quite important for Voodoo to be popular that it works on 14.04 too..

**Comment by rvalyi** [comment]
Here we got voodoo 2 working successfully on Ubuntu 14.04. So in your case I really think all your need is update your docker deb package and try again.
