### ISSUE TITLE
sudo in docker voodoo

### ISSUE THREAD

**Issue by bealdav** [akretion/voodoo#58]
I think than in dev mode we could restore the possibility to use sudo in docker.

It allows to avoid limitations to test some libs or debug ak

I don't know if it's difficult to separate the behavior according to production env or not.

**Comment by rvalyi** [comment]
:+1:

**Comment by sebastienbeau** [comment]
I do not thinks it a good idea. I prefer to have only one image for dev and prod (it will avoid someday to have the sudo feature in production by error). And it simplify the maintenance (having two images)

If you need to add custom debian package or you need a temporary root access you can do it by generating a custom Dockerfile see documentation here : https://github.com/akretion/voodoo/wiki/Install-custom-debian-package.
Note if you want that you local docker start in root you just have to set the following code in your local DockerFile 

```
FROM akretion/voodoo:latest
USER root
```
