### ISSUE TITLE
Resolv not work with project folder with Upper Case

### ISSUE THREAD

**Issue by EBII** [akretion/voodoo#75]
if folder project use upperCase  like V10toto
in the browser you can not access any http://V10toto:8069 or http://v10toto:8069

you need to change in dev.resolv.conf  the container name with lowercase
container_name: v10toto 
and use the url http://v10toto:8069

**Comment by sebastienbeau** [comment]
fixed here : https://github.com/akretion/voodoo/commit/4791453f9951fe804af321ac504bb1fa96479eef
