### ISSUE TITLE
ak build fails due to pychart

### ISSUE THREAD

**Issue by R-2-D-2** [akretion/voodoo#81]
Hi there,
I'm trying to setup Odoo 9 via Voodoo. I followed the docs but the "ak build" command fails because the "download.gna.org" domain seems to be down (response 504). 

Is anyone aware of this issue?

I wasn't able to find an alternative source of pychart. The only one I found is the GitHub repo which I tried to install (I extended the Dockerfile to become root and tried to manually install it - did not work).

Could someone give me a hint how to work around the pychart issue?

Best,
Sascha

**Comment by mbcosta** [comment]
Hi Sascha
    Take a look https://github.com/OCA/maintainer-quality-tools/pull/446/files , just remove the line about pychart from buildout.cfg and try to make "ak build" again. In a update voodoo the version 10.0 work fine.

**Comment by R-2-D-2** [comment]
Hi mbcosta,
thanks for your reply! I I was testing Odoo 8 and found a slightly different approach to solve the issue. I removed the pychart line - as you suggested - and modified the `buildout.dev.cfg` like below.

```
[buildout]
extensions += gp.vcsdevelop
vcs-extend-develop = git+https://github.com/anybox/anybox.recipe.odoo@e37e0ac527de58abe6e913e4eff670d2f8d72c9a#egg=anybox.recipe.odoo
#vcs-extend-develop = bzr+http://bazaar.launchpad.net/~openerp/openerp-command/trunk#egg=openerp-command
vcs-update = true
extends = frozen.cfg
```
Which seems to work so far.

Cheers

**Comment by bealdav** [comment]
@R-2-D-2  Yes I fixed v8 version. 

If you work on v9 could you make a similar PR for v9 voodoo-template ?

Thanks
