### ISSUE TITLE
template 10.0 doesn't work

### ISSUE THREAD

**Issue by Peamcy** [akretion/voodoo#83]
following strictly the documentation, i can't create a new project based on 10.0 template. pathspec '10.0' did not match any file(s) known to git.

**Comment by bealdav** [comment]
I confirm the behavior.

Voodoo is broken for now  :-(

**Comment by EBII** [comment]
at this time you can use voodoo with 10.0 with uncomment the 3 first line in buidout.dev.cfg

**Comment by rvalyi** [comment]
This should be fixed now...
@florian-dacosta it seems you are the culprit as you removed the 10.0 branch of akretion/voodoo-template by mistake recently. I pushed it again. @Peamcy can you confirm it works again for you?
cc @sebastienbeau
